-- AlterTable
ALTER TABLE "EventsServices" ADD COLUMN     "reallyMashguiachArrive" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "reallyMashguiachEndTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
