version: "3.9"
services:
  database:
    image: postgis/postgis:13-3.3
    container_name: byk-database
    volumes:
      - "./.docker/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=byk
      - POSTGRES_PASSWORD=bykpassword
      - POSTGRES_DB=byk
  # server:
  #   build: .
  #   container_name: rewrite_server
  #   ports:
  #     - "3050:3050"
  #   environment:
  #     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  #     - S3_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - S3_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - S3_REGION=${AWS_REGION}
  #     - DATABASE_URL=postgres://root:root@database:5432/db
  #     - TYPEORM_MIGRATIONS_DIR=./dist/shared/infra/typeorm/migrations/*{.ts,.js}
  #     - TYPEORM_ENTITIES_DIR=./dist/**/modules/**/entities/*{.ts,.js}
  #     - AOCUBO_JWT_EXPIRES_IN=10d
  #   depends_on:
  #     - database